### ISSUE TITLE
Problems with memory kinds in OFI conduit

### ISSUE THREAD

**Issue by elliottslaughter** [StanfordLegion/gasnet#27]
I've had multiple users independently report issues with memory kinds support in OFI conduit, originally added in #26. I have rolled back the change in 942ef8306feda0a9436bdc5aa658088daa554c9c until we sort through what is going on. This issue will serve as a tracker for the various symptoms.

Here's my recollection of what has been reported to me:

User A: reported on Perlmutter hitting the following:

```
*** FATAL ERROR (proc 0): in gasnetc_rdma_put() at anguage/gasnet/GASNet-2023.9.0/ofi-conduit/gasnet_ofi.c:2849: fi_write failed: 12(Cannot allocate memory)
```

User B: reported "performances issues", waiting for more details.

For myself: on Frontier, I hit a segfault when trying to turn on memory kinds, and was advised to try a debug GASNet. (I have not yet had time.)

**Comment by bonachea** [comment]
I'm sorry to hear that your users are encountering problems. The UPC++ runtime has been successfully using ofi-conduit's CUDA and HIP memory kinds on Slingshot-11 since they were introduced in [2022.9.0](https://bitbucket.org/berkeleylab/upcxx/wiki/ChangeLog#markdown-header-20220930-release-202290), so I can attest this feature is not completely broken. We may just need to track down what differs in Realm's usage.

The behaviors you describe sound like potentially/likely separate problems. As such, I'd suggest creating independent issues for each symptom and linking each from here, rather than trying to interleave triage for all the different problems in a single issue.

**Comment by tukss** [comment]
We've had some performance issues that were fixed by rolling back that change. On a HIP system running on a single GPU the performance of GPU kernels was about a factor of 30 slower when we used tracing in the code. Interestingly the code ran with its normal performance as soon as the Legion profiler was switched on. I wonder if it has any side effect that could cause this.

**Comment by elliottslaughter** [comment]
Just to close the loop on this: I believe that User A's case in https://github.com/StanfordLegion/gasnet/issues/27#issue-2204850928 was confirmed to be an instance of https://github.com/StanfordLegion/legion/issues/1681 and therefore should be fixed by https://gitlab.com/StanfordLegion/legion/-/merge_requests/1244 (when GASNet memory kinds are enabled at compile time). At least it will be a hard error now; of course the issue of how much GPU memory can actually be pinned with a given NIC is still a problem (but one outside of our control).

The other issue (regarding performance) was split off into #28.

I think those are all the known issues with memory kinds at this time.

**Comment by elliottslaughter** [comment]
Closing because I think we have a handle on these failure modes now, except #28 which has its own issue.
