### ISSUE TITLE
Enable pshm by default.

### ISSUE THREAD

**Issue by syamajala** [StanfordLegion/gasnet#6]
GASNet 2022.9.0 recommends enabling pshm by default when running multiple ranks/host. We currently disable it by default. I have tested on Summit using IBV, and Crusher and Perlmutter using OFI conduits with S3D and have not had any problems. 

I think we can also make 2022.9.0 the default version we build.

**Comment by elliottslaughter** [comment]
This seems reasonable to me. I think we were suspicious in the beginning, and wanted to keep it off to minimize complexity, but I don't think I've ever had a negative experience with it.

@streichler what do you think?

**Comment by streichler** [comment]
Given that there are external factors that encourage (or even force) us in some cases to run multiple ranks/node these days, I do think it's reasonable to turn this on by default.  @syamajala, what scale did you test this at on summit and/or perlmutter, and did you look for performance differences or just correct functionality?

**Comment by bonachea** [comment]
In case it helps solidify your decision, here are a few additional arguments in favor of enabling PSHM:

1. UPC++ and the Berkeley UPC runtime (with all four translators) have enabled PSHM by default since its inception, and we've never measured a downside to doing so, even for single-PPN jobs (although those are admittedly rare in these programming models).
2. The majority of our automated testing and all our UPC/UPC++ application runs use the GASNet PSHM transport, and we have high confidence in its robustness, performance and portability.
2. Since last year's 2021.9.0 release, the "same node, use PSHM" check for is now fully "merged" with the "same process, do loopback" check (which was always present in all modes), meaning there is no additional dynamic branch along the network injection path for PSHM support, even for 1-PPN runs. 
3. For multi-PPN runs, intranode operations following the PSHM transport are routinely and literally orders of magnitude more efficient than anything involving the network adapter or PCI bus, even for the best networks.
4. The resources used for the shared-memory transport are completely disjoint from the network transport in all conduits. This means multi-PPN jobs using PSHM for intra-node comms allows network resources (buffers, flow-control credits, etc) to be dedicated to inter-node comms, which can measurably increase global throughput. 

These benefits can have a major impact on performance of all multi-PPN jobs, and applications that optimize for hierarchical locality and favor communication with on-node peers stand to benefit even further.

**Comment by elliottslaughter** [comment]
I updated the default version to 2022.9.0.

@streichler what do you need to set to be comfortable enabling PSHM by default?

**Comment by elliottslaughter** [comment]
I have enabled PSHM on all conduits.

**Comment by elliottslaughter** [comment]
Just FYI, PSHM created complications for our tests on the MPI conduit:

https://gitlab.com/StanfordLegion/legion/-/jobs/3287327360
https://gitlab.com/StanfordLegion/legion/-/jobs/3288313264

I turned off PSHM for MPI conduit for now. I left the others on.

I don't think we *really* care strongly about PSHM for MPI either way, but I figured I'd mention it in case it's something @bonachea wants to look into.

**Comment by bonachea** [comment]
@elliottslaughter wrote:
> I turned off PSHM for MPI conduit for now. ... I had to roll back UCX as well
>
>  I figured I'd mention it in case it's something @bonachea wants to look into.

We would very much like to help shake out any problems necessary to get Legion testing "fully" on PSHM. However I'm unfamiliar with Legion's CI and rightly lack privileges to change anything, so this will need to be a collaborative process. 

As this issue is already closed, I'll open new issues to track the specific failures.
